### ISSUE TITLE
Publishing/Including CUDA dll's

### ISSUE THREAD

**Issue by matbeedotcom** [ForserX/StableDiffusionUI#19]
Is it possible to package a version of this that includes all necessary CUDA libraries, and Python? 
Is there a redistributable cuda/python runtime installer package, like .NET?
It would be great to have a FAQ.

**Comment by ForserX** [comment]
Python + CUDA ~5 GB. 
But that's not even the problem. I am the owner of an AMD video card, which is why I simply cannot install CUDA dependencies.
> Is there a redistributable cuda/python runtime installer package, like .NET?

IDK. SD library use Python by default. I make only UI into C#. (Well, the implementation of the execution itself and some extensions of the functionality in Python.)
